### PR TITLE
Update the repo to have a leftside nav when in mobile viewport range

### PR DESCRIPTION
**Pull request by stormy251**
Playing around with a left hand expandable navigation system for mobile.

### CODE REVIEW

**Comment by stormy251** [comment]
Check this one out on your phone bro let me know whatcha think

**Comment by dougcpr** [comment]
What about atlassian's design of using an arrow to expand the nav icons and show a text field?
For example in Atlassian:
Screen Shot 2020-02-25 at 7 29 39 AM

Screen Shot 2020-02-25 at 7 29 47 AM

**Comment by stormy251** [comment]
@dougcpr That looks really nice, I was noticing that with this design we are constraining the width of the actual content on mobile because the side bar is "always there"... so I wanted to revisit this design a good bit.

**Comment by stormy251** [comment]
@dougcpr That looks really nice, I was noticing that with this design we are constraining the width of the actual content on mobile because the side bar is "always there"... so I wanted to revisit this design a good bit.

**Comment by stormy251** [comment]
Closing this as it is really not the direction I would like to go in terms of mobile navigation

**Pull request closed without merging**
